name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc -o elero main.h main.c
    - name: build-tests
      run: gcc -o elero_tests main.h tests.c
    - name: run-tests
      run: ./elero_tests
